### ISSUE TITLE
BUG: Retrieving Adjudications for an Occupancy

### ISSUE THREAD

**Issue by drewbotts** [Botts-Innovative-Research/oscar-viewer#137]
It appears that we are retrieving any adjudications for that lane, rather than for that specific occupancy. I saw there is a filter for occupancy id check box but I have yet to get that to work. This table should only show adjudications for this occupancy.

**Comment by ChainReaction31** [comment]
It's either an issue with adjudicated items not being in the table when the fetch happens on the app initializing or with items not being filtered correctly on submission since they're not retrieved from the node again after that. For me it worked but there were no logged adjudications at the time since the way you get there from the main dashboard is through the event you're already adjudicating.

**Comment by ChainReaction31** [comment]
I think this was solved by 0623b53
